# Serveur 
server.port=8085

#Base de donnees H2 en memoire 
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate 
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Console H2 (acces via /h2-console) 
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#  Actuator (pour healthcheck.sh)
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Infos application
spring.application.name=springbash
info.app.name=ENS SpringBash
info.app.version=1.0.0
info.app.description=TP 14 - Automatisation et Deploiement avec Bash
